channels:
- conda-forge
dependencies:
- python=3.10.0
- pip<=23.3.1
- pip:
  - mlflow==2.9.2
  - cloudpickle==3.0.0
  - numpy==1.26.3
  - packaging==23.2
  - pandas==2.1.4
  - pyyaml==6.0.1
  - scikit-learn==1.4.0
  - scipy==1.11.4
  - xgboost==2.0.3
name: mlflow-env
